# Generated by Django 2.2.16 on 2021-12-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('users', '0002_auto_20211222_1840'), ('users', '0003_auto_20211225_1111')]

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
