# Generated by Django 2.2.16 on 2021-12-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['pk']},
        ),
    ]
