# Generated by Django 2.2.16 on 2021-12-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211222_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['pk']},
        ),
    ]
