# Generated by Django 2.2.16 on 2021-12-16 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('reviews', '0003_auto_20211216_1858'), ('reviews', '0004_auto_20211216_1905')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20211216_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
